# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Studying Machine Learning, One Step at a Time
description: This blog documents my journey into machine learning as a Biology and Neuroscience student with a foundational background in computer science. Before starting this journey, I completed introductory Python and Java courses, alongside a computational neuroscience course at my university. I familiarized myself with the majority of the programming concepts detailed in "Building Python Programs" by Stuart Reges, Marty Stepp, and Allison Obourn. In the three weeks leading up to the start of this blog, I dedicated my time to studying the following materials: I completed Coursera lectures on "Neural Networks and Deep Learning" and "Improving Deep Neural Networks: Hyperparameter Tuning, Regularization, and Optimization," both taught by Andrew Ng. I also devoted considerable effort to understanding the first chapter of "Neural Networks and Deep Learning" by Michael Nielsen, to the extent that I could personally visualize and explain every segment of the code for the digit identifier. Complementing these were the two 3Blue1Brown YouTube series on the essence of linear algebra and neural networks. Finally, my exploration led me to the first two lectures by Jeremy Howard on the fast.ai website and the initial one and a half chapters of "Deep Learning for Coders with fastai & PyTorch AI Applications Without a PhD" by Jeremy Howard and Sylvain Gugger. The impetus to start this blog came from the second chapter of "Deep Learning for Coders with fastai & PyTorch AI Applications Without a PhD," which prompted me to share my thoughts and experiences as I delve deeper into the field of machine learning.
github_username: morekim2020

# Email and twitter are optional:
email: morekim2020@gmail.com
twitter_username: MoReKim_2020

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
